export const INSTAGRAM = 'https://instagram.com/coachk_experience/'
export const TWITTER = 'https://twitter.com/ck_conference/status/1509035692550066182'
export const TELEGRAM = 'https://t.me/coachk_conference_ann'
export const YOUTUBE = 'https://youtube.com/c/coachkcrypto'
export const FORM = 'https://coachk.vip/conference-book'
